/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author YO
 */
public class frmAdministrador extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmAdministrador
     */
    public frmAdministrador() {
        initComponents();
    }

    public JButton getBtnEntregar() {
        return btnEntregar;
    }

    public void setBtnEntregar(JButton btnEntregar) {
        this.btnEntregar = btnEntregar;
    }

    public JButton getBtnEntregarP() {
        return btnEntregarP;
    }

    public void setBtnEntregarP(JButton btnEntregarP) {
        this.btnEntregarP = btnEntregarP;
    }

    public JButton getBtnPagarCorte() {
        return btnPagarCorte;
    }

    public void setBtnPagarCorte(JButton btnPagarCorte) {
        this.btnPagarCorte = btnPagarCorte;
    }

    public JLabel getLblAdmi() {
        return lblAdmi;
    }

    public void setLblAdmi(JLabel lblAdmi) {
        this.lblAdmi = lblAdmi;
    }

    public JLabel getLblElliminarCorte() {
        return lblElliminarCorte;
    }

    public void setLblElliminarCorte(JLabel lblElliminarCorte) {
        this.lblElliminarCorte = lblElliminarCorte;
    }

    public JLabel getLblPagar() {
        return lblPagar;
    }

    public void setLblPagar(JLabel lblPagar) {
        this.lblPagar = lblPagar;
    }

    public JTable getTblCorteXEntregar() {
        return tblCorteXEntregar;
    }

    public void setTblCorteXEntregar(JTable tblCorteXEntregar) {
        this.tblCorteXEntregar = tblCorteXEntregar;
    }

    public JTable getTblCorteXPagar() {
        return tblCorteXPagar;
    }

    public void setTblCorteXPagar(JTable tblCorteXPagar) {
        this.tblCorteXPagar = tblCorteXPagar;
    }

    public JTable getTblCortesEntregados() {
        return tblCortesEntregados;
    }

    public void setTblCortesEntregados(JTable tblCortesEntregados) {
        this.tblCortesEntregados = tblCortesEntregados;
    }

    public JTable getTblCortesPendientes() {
        return tblCortesPendientes;
    }

    public void setTblCortesPendientes(JTable tblCortesPendientes) {
        this.tblCortesPendientes = tblCortesPendientes;
    }

    public JTextField getTxtEliminarCorte() {
        return txtEliminarCorte;
    }

    public void setTxtEliminarCorte(JTextField txtEliminarCorte) {
        this.txtEliminarCorte = txtEliminarCorte;
    }

    public JTextField getTxtPagar() {
        return txtPagar;
    }

    public void setTxtPagar(JTextField txtPagar) {
        this.txtPagar = txtPagar;
    }

    public JLabel getLblMensaje() {
        return lblMensaje;
    }

    public void setLblMensaje(JLabel lblMensaje) {
        this.lblMensaje = lblMensaje;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnEntregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnEntregarP = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCorteXEntregar = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCortesPendientes = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lblAdmi = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCortesEntregados = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblCorteXPagar = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtPagar = new javax.swing.JTextField();
        btnPagarCorte = new javax.swing.JButton();
        lblPagar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEliminarCorte = new javax.swing.JTextField();
        lblElliminarCorte = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N
        jLabel4.setText("Cortes Entregados");

        btnEntregar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N
        btnEntregar.setText("Entregar");

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N
        jLabel1.setText("Cortes Por Entregar");

        btnEntregarP.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N
        btnEntregarP.setText("Entregar Pendiente");

        tblCorteXEntregar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N
        tblCorteXEntregar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCorteXEntregar);

        tblCortesPendientes.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N
        tblCortesPendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblCortesPendientes);

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N
        jLabel3.setText("Cortes Pendientes");

        lblAdmi.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N
        lblAdmi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tblCortesEntregados.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N
        tblCortesEntregados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblCortesEntregados);

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N
        jLabel2.setText("Cortes Por Pagar");

        tblCorteXPagar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N
        tblCorteXPagar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblCorteXPagar);

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N
        jLabel7.setText("Ingrese ID Para Realizar Pago");

        txtPagar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N

        btnPagarCorte.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N
        btnPagarCorte.setText("Pagar");

        lblPagar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N
        jLabel5.setText("Eliminar Corte");

        txtEliminarCorte.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N

        lblElliminarCorte.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N
        lblElliminarCorte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAdmi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnEntregar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblMensaje))
                                    .addComponent(btnEntregarP)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPagarCorte)
                                .addGap(18, 18, 18)
                                .addComponent(lblPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEliminarCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblElliminarCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 127, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAdmi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntregar)
                    .addComponent(lblMensaje))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPagarCorte)
                        .addComponent(jLabel7)
                        .addComponent(txtPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPagar))
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEntregarP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtEliminarCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblElliminarCorte))
                .addGap(25, 25, 25))
        );

        jScrollPane4.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntregar;
    private javax.swing.JButton btnEntregarP;
    private javax.swing.JButton btnPagarCorte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblAdmi;
    private javax.swing.JLabel lblElliminarCorte;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblPagar;
    private javax.swing.JTable tblCorteXEntregar;
    private javax.swing.JTable tblCorteXPagar;
    private javax.swing.JTable tblCortesEntregados;
    private javax.swing.JTable tblCortesPendientes;
    private javax.swing.JTextField txtEliminarCorte;
    private javax.swing.JTextField txtPagar;
    // End of variables declaration//GEN-END:variables
}
