/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author YO
 */
public class frmCorte extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmCorte
     */
    public frmCorte() {
        initComponents();
    }

    public JButton getBtnRegresar() {
        return btnRegresar;
    }

    public void setBtnRegresar(JButton btnRegresar) {
        this.btnRegresar = btnRegresar;
    }
    

    public JButton getBtnConsColores() {
        return btnConsColores;
    }

    public void setBtnConsColores(JButton btnConsColores) {
        this.btnConsColores = btnConsColores;
    }

    public JButton getBtnConsGanancias() {
        return btnConsGanancias;
    }

    public void setBtnConsGanancias(JButton btnConsGanancias) {
        this.btnConsGanancias = btnConsGanancias;
    }

    public JButton getBtnConsTallas() {
        return btnConsTallas;
    }

    public void setBtnConsTallas(JButton btnConsTallas) {
        this.btnConsTallas = btnConsTallas;
    }

    public JButton getBtnConsTareas() {
        return btnConsTareas;
    }

    public void setBtnConsTareas(JButton btnConsTareas) {
        this.btnConsTareas = btnConsTareas;
    }

    public JLabel getLblInsumos() {
        return lblInsumos;
    }

    public void setLblInsumos(JLabel lblInsumos) {
        this.lblInsumos = lblInsumos;
    }

    public JTable getTblConsultas() {
        return tblConsultas;
    }

    public void setTblConsultas(JTable tblConsultas) {
        this.tblConsultas = tblConsultas;
    }

    public JTable getTblCortes() {
        return tblCortes;
    }

    public void setTblCortes(JTable tblCortes) {
        this.tblCortes = tblCortes;
    }

    public JTextField getTxtInsumos() {
        return txtInsumos;
    }

    public void setTxtInsumos(JTextField txtInsumos) {
        this.txtInsumos = txtInsumos;
    }

    public JButton getBtnEliminarColor() {
        return btnEliminarColor;
    }

    public void setBtnEliminarColor(JButton btnEliminarColor) {
        this.btnEliminarColor = btnEliminarColor;
    }

    public JButton getBtnEliminarTalla() {
        return btnEliminarTalla;
    }

    public void setBtnEliminarTalla(JButton btnEliminarTalla) {
        this.btnEliminarTalla = btnEliminarTalla;
    }

    public JList<String> getListaCortes() {
        return listaCortes;
    }

    public void setListaCortes(JList<String> listaCortes) {
        this.listaCortes = listaCortes;
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblConsultas = new javax.swing.JTable();
        txtInsumos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCortes = new javax.swing.JTable();
        btnConsColores = new javax.swing.JButton();
        btnConsTallas = new javax.swing.JButton();
        btnConsGanancias = new javax.swing.JButton();
        btnConsTareas = new javax.swing.JButton();
        lblInsumos = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnEliminarColor = new javax.swing.JButton();
        btnEliminarTalla = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaCortes = new javax.swing.JList<>();

        setResizable(true);

        tblConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblConsultas);

        jLabel1.setFont(new java.awt.Font("Sitka Small", 0, 14)); // NOI18N
        jLabel1.setText("Consultar Corte(s)");

        tblCortes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCortes);

        btnConsColores.setText("Colores");

        btnConsTallas.setText("Tallas");

        btnConsGanancias.setText("Ganancias");

        btnConsTareas.setText("Tareas");
        btnConsTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsTareasActionPerformed(evt);
            }
        });

        lblInsumos.setFont(new java.awt.Font("Lucida Handwriting", 0, 11)); // NOI18N
        lblInsumos.setText("Ingrese Insumos");

        btnRegresar.setText("Regresar");

        btnEliminarColor.setText("Eliminar");

        btnEliminarTalla.setText("Eliminar");

        jScrollPane3.setViewportView(listaCortes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnConsColores, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEliminarColor)
                                    .addComponent(btnEliminarTalla))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnConsTallas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnConsTareas, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnConsGanancias, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblInsumos)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addComponent(txtInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(52, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsColores)
                    .addComponent(btnConsTallas)
                    .addComponent(btnConsTareas)
                    .addComponent(btnConsGanancias))
                .addGap(18, 18, 18)
                .addComponent(btnEliminarColor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInsumos)
                    .addComponent(btnEliminarTalla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(273, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsTareasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsTareasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsColores;
    private javax.swing.JButton btnConsGanancias;
    private javax.swing.JButton btnConsTallas;
    private javax.swing.JButton btnConsTareas;
    private javax.swing.JButton btnEliminarColor;
    private javax.swing.JButton btnEliminarTalla;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblInsumos;
    private javax.swing.JList<String> listaCortes;
    private javax.swing.JTable tblConsultas;
    private javax.swing.JTable tblCortes;
    private javax.swing.JTextField txtInsumos;
    // End of variables declaration//GEN-END:variables
}
