/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author YO
 */
public class    frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        //setIconImage(new ImageIcon(getClass().getResource("../img/CONFECCION.png")).getImage());
    }

    public JDesktopPane getJdpEscritorio() {
        return jdpEscritorio;
    }

    public void setJdpEscritorio(JDesktopPane jdpEscritorio) {
        this.jdpEscritorio = jdpEscritorio;
    }

    public JLabel getLblFecha() {
        return lblFecha;
    }   

    public void setLblFecha(JLabel lblFecha) {
        this.lblFecha = lblFecha;
    }

    public JMenuBar getMenu() {
        return Menu;
    }

    public void setMenu(JMenuBar Menu) {
        this.Menu = Menu;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpEscritorio = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        lblFecha = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        opmNuevo = new javax.swing.JMenuItem();
        opmConsultar = new javax.swing.JMenuItem();
        opmAsignarTareas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        opmNominaC = new javax.swing.JMenuItem();
        opmNominaU = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        opmRegProveedor = new javax.swing.JMenuItem();
        opmRegOperario = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        opmProveedor = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        opmSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jdpEscritorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        jdpEscritorio.setPreferredSize(new java.awt.Dimension(715, 732));

        jToolBar1.setRollover(true);

        lblFecha.setFont(new java.awt.Font("Perpetua Titling MT", 0, 12)); // NOI18N
        lblFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jToolBar1.add(lblFecha);

        jdpEscritorio.setLayer(jToolBar1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpEscritorioLayout = new javax.swing.GroupLayout(jdpEscritorio);
        jdpEscritorio.setLayout(jdpEscritorioLayout);
        jdpEscritorioLayout.setHorizontalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpEscritorioLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 598, Short.MAX_VALUE))
        );
        jdpEscritorioLayout.setVerticalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdpEscritorioLayout.createSequentialGroup()
                .addGap(0, 653, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Menu.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N

        jMenu1.setText("Corte");
        jMenu1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N

        opmNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        opmNuevo.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        opmNuevo.setText("Nuevo");
        opmNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opmNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(opmNuevo);

        opmConsultar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        opmConsultar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        opmConsultar.setText("Consultar");
        jMenu1.add(opmConsultar);

        opmAsignarTareas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        opmAsignarTareas.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        opmAsignarTareas.setText("Asignar Tareas");
        jMenu1.add(opmAsignarTareas);

        Menu.add(jMenu1);

        jMenu2.setText("Nomina");
        jMenu2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N

        opmNominaC.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        opmNominaC.setText("Nomina Completa");
        opmNominaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opmNominaCActionPerformed(evt);
            }
        });
        jMenu2.add(opmNominaC);

        opmNominaU.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        opmNominaU.setText("Nomina Unica");
        jMenu2.add(opmNominaU);

        Menu.add(jMenu2);

        jMenu3.setText("Registrar");
        jMenu3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N

        opmRegProveedor.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        opmRegProveedor.setText("Proveedor");
        jMenu3.add(opmRegProveedor);

        opmRegOperario.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        opmRegOperario.setText("Operario");
        jMenu3.add(opmRegOperario);

        Menu.add(jMenu3);

        jMenu6.setText("Proveedor");
        jMenu6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N

        opmProveedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        opmProveedor.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        opmProveedor.setText("Buscar");
        jMenu6.add(opmProveedor);

        Menu.add(jMenu6);

        jMenu4.setText("Salir");
        jMenu4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 13)); // NOI18N

        opmSalir.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        opmSalir.setText("Salir");
        jMenu4.add(opmSalir);

        Menu.add(jMenu4);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opmNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opmNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opmNuevoActionPerformed

    private void opmNominaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opmNominaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opmNominaCActionPerformed

    
    
    public JMenuItem getOpmAsignarTareas() {
        return opmAsignarTareas;
    }

    public void setOpmAsignarTareas(JMenuItem opmAsignarTareas) {
        this.opmAsignarTareas = opmAsignarTareas;
    }

    public JMenuItem getOpmConsultar() {
        return opmConsultar;
    }

    public void setOpmConsultar(JMenuItem opmConsultar) {
        this.opmConsultar = opmConsultar;
    }

    public JMenuItem getOpmNominaC() {
        return opmNominaC;
    }

    public void setOpmNominaC(JMenuItem opmNominaC) {
        this.opmNominaC = opmNominaC;
    }

    public JMenuItem getOpmNominaU() {
        return opmNominaU;
    }

    public void setOpmNominaU(JMenuItem opmNominaU) {
        this.opmNominaU = opmNominaU;
    }

    public JMenuItem getOpmNuevo() {
        return opmNuevo;
    }

    public void setOpmNuevo(JMenuItem opmNuevo) {
        this.opmNuevo = opmNuevo;
    }

    public JMenuItem getOpmProveedor() {
        return opmProveedor;
    }

    public void setOpmProveedor(JMenuItem opmProveedor) {
        this.opmProveedor = opmProveedor;
    }

    public JMenuItem getOpmRegOperario() {
        return opmRegOperario;
    }

    public void setOpmRegOperario(JMenuItem opmRegOperario) {
        this.opmRegOperario = opmRegOperario;
    }

    public JMenuItem getOpmRegProveedor() {
        return opmRegProveedor;
    }

    public void setOpmRegProveedor(JMenuItem opmRegProveedor) {
        this.opmRegProveedor = opmRegProveedor;
    }

    public JMenuItem getOpmSalir() {
        return opmSalir;
    }

    public void setOpmSalir(JMenuItem opmSalir) {
        this.opmSalir = opmSalir;
    }    

    public JMenu getjMenu6() {
        return jMenu6;
    }

    public void setjMenu6(JMenu jMenu6) {
        this.jMenu6 = jMenu6;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDesktopPane jdpEscritorio;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JMenuItem opmAsignarTareas;
    private javax.swing.JMenuItem opmConsultar;
    private javax.swing.JMenuItem opmNominaC;
    private javax.swing.JMenuItem opmNominaU;
    private javax.swing.JMenuItem opmNuevo;
    private javax.swing.JMenuItem opmProveedor;
    private javax.swing.JMenuItem opmRegOperario;
    private javax.swing.JMenuItem opmRegProveedor;
    private javax.swing.JMenuItem opmSalir;
    // End of variables declaration//GEN-END:variables
}
