/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author YO
 */
public class frmVerProveedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmVerProveedor
     */
    public frmVerProveedor() {
        initComponents();
    }

    public JButton getBtnModelos() {
        return btnModelos;
    }

    public void setBtnModelos(JButton btnModelos) {
        this.btnModelos = btnModelos;
    }

    public JLabel getLblCorreoRepresentante() {
        return lblCorreoRepresentante;
    }

    public void setLblCorreoRepresentante(JLabel lblCorreoRepresentante) {
        this.lblCorreoRepresentante = lblCorreoRepresentante;
    }

    public JLabel getLblIDProv() {
        return lblIDProv;
    }

    public void setLblIDProv(JLabel lblIDProv) {
        this.lblIDProv = lblIDProv;
    }

    public JLabel getLblIdRepresentante() {
        return lblIdRepresentante;
    }

    public void setLblIdRepresentante(JLabel lblIdRepresentante) {
        this.lblIdRepresentante = lblIdRepresentante;
    }

    public JLabel getLblNombreRepresentante() {
        return lblNombreRepresentante;
    }

    public void setLblNombreRepresentante(JLabel lblNombreRepresentante) {
        this.lblNombreRepresentante = lblNombreRepresentante;
    }

    public JLabel getLblNombreProv() {
        return lblNombreProv;
    }

    public void setLblNombreProv(JLabel lblNombreProv) {
        this.lblNombreProv = lblNombreProv;
    }

    public JTable getTblRepresentantes() {
        return tblRepresentantes;
    }

    public void setTblRepresentantees(JTable tblRepresentantees) {
        this.tblRepresentantes = tblRepresentantees;
    }

    public JTextField getTxtIdRepresentante() {
        return txtIdRepresentante;
    }

    public void setTxtIdRepresentante(JTextField txtIdRepresentante) {
        this.txtIdRepresentante = txtIdRepresentante;
    }

    public JButton getBtnRegresar() {
        return btnRegresar;
    }

    public JLabel getLblMensaje() {
        return lblMensaje;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRepresentantes = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdRepresentante = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblNombreRepresentante = new javax.swing.JLabel();
        lblIdRepresentante = new javax.swing.JLabel();
        lblCorreoRepresentante = new javax.swing.JLabel();
        btnModelos = new javax.swing.JButton();
        lblNombreProv = new javax.swing.JLabel();
        lblIDProv = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 15)); // NOI18N
        jLabel1.setText("Informacion");

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 15)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 15)); // NOI18N
        jLabel3.setText("Identificacion");

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 15)); // NOI18N
        jLabel4.setText("Representantes");

        tblRepresentantes.setFont(new java.awt.Font("Perpetua Titling MT", 1, 15)); // NOI18N
        tblRepresentantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRepresentantes);

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 15)); // NOI18N
        jLabel5.setText("Buscar Representante");

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 15)); // NOI18N
        jLabel6.setText("Ingrese ID");

        txtIdRepresentante.setFont(new java.awt.Font("Perpetua Titling MT", 1, 15)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 15)); // NOI18N
        jLabel7.setText("Nombre");

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 1, 15)); // NOI18N
        jLabel8.setText("ID");

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 1, 15)); // NOI18N
        jLabel9.setText("Correo");

        lblNombreRepresentante.setFont(new java.awt.Font("Perpetua Titling MT", 1, 15)); // NOI18N
        lblNombreRepresentante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lblIdRepresentante.setFont(new java.awt.Font("Perpetua Titling MT", 1, 15)); // NOI18N
        lblIdRepresentante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lblCorreoRepresentante.setFont(new java.awt.Font("Perpetua Titling MT", 1, 15)); // NOI18N
        lblCorreoRepresentante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        btnModelos.setFont(new java.awt.Font("Perpetua Titling MT", 1, 15)); // NOI18N
        btnModelos.setText("Modelos");

        lblNombreProv.setFont(new java.awt.Font("Perpetua Titling MT", 1, 15)); // NOI18N
        lblNombreProv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lblIDProv.setFont(new java.awt.Font("Perpetua Titling MT", 1, 15)); // NOI18N
        lblIDProv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        btnRegresar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 15)); // NOI18N
        btnRegresar.setText("Regresar");

        lblMensaje.setFont(new java.awt.Font("Perpetua Titling MT", 1, 15)); // NOI18N
        lblMensaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreRepresentante)
                            .addComponent(jLabel7))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblIdRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(lblCorreoRepresentante))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel8)
                                .addGap(79, 79, 79)
                                .addComponent(jLabel9))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnModelos))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreProv, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIDProv, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(btnRegresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel1)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombreProv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblIDProv, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtIdRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMensaje))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblNombreRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCorreoRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnModelos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegresar)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModelos;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCorreoRepresentante;
    private javax.swing.JLabel lblIDProv;
    private javax.swing.JLabel lblIdRepresentante;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNombreProv;
    private javax.swing.JLabel lblNombreRepresentante;
    private javax.swing.JTable tblRepresentantes;
    private javax.swing.JTextField txtIdRepresentante;
    // End of variables declaration//GEN-END:variables
}
